[package]
name = "qrusty"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.21"
copypasta = "0.10.1"
device_query = "2.1.0"
image = "0.25.5"
notify-rust = "4.11.3"
rqrr = "0.8.0"
xcap = "0.0.14"
